### PR TITLE
Shared configuration setup

### PR DESCRIPTION
**Pull request by aisthesis**

### CODE REVIEW

**Comment by mscappini** [comment]
I'm a little confused by the `process.env.npm_config_quichean_nconf_path`. Specifically `quichean_nconf_path`. This is a value you set with `npm config set quichean:nconf:path`? Why the scoping with the word "quichean"? Why not something more relevant like "optbot_pytools"? Was this intentional?

**Comment by aisthesis** [comment]
'quichean' is a synonym for 'optbot'. The domain 'optbot.com' is not available and probably wouldn't be a great domain name anyway. I own 'quichean.com', which will be the domain for the actual site when we have it running. This is a single configuration, so it wouldn't be correct to scope it with 'pytools'. The name is derived from the scoping you suggested when we were having the discussion in connection with `cfgloader`. I just expanded the abbreviated 'ob' part to 'quichean', since it is _guaranteed_ that that is our namespace and that there won't be any conflicts. It's probably overkill, but it should certainly work, and I don't see any downside to naming it that way.

Just to clarify, I'm not looking for a path that has anything to do with `pytools` with that variable. I'm looking for the place where all of our `nconf` configurations are to be stored. The specifics having to do with `pytools` and any other services that need to share python configurations are dealt with by `nconf`. We just need to know where to go to find the `nconf` configurations without being dependent on a specific user.

**Comment by aisthesis** [comment]
https://github.com/aisthesis/quichean/wiki/Configuration#global-configurations

**Comment by mscappini** [comment]
That makes more sense. I'm still looking for a way to not use `nconf` if possible, but I'll continue down that path on my own as to not waste anybody else's time.

Looks okay to merge.

**Pull request merged**
